function InputTab(props) {
  const {
    allMonths, filterJenis, filterMonth, form, handleDelete, handleExport, handleSubmit,
    setEditTx, syncing, histFiltered, histGrouped, histPemasukan, histPengeluaran,
    inputSubTab, isSearching, jenisKat, myName, oldMonthMin, oldTxCount, sbAddFriend,
    sbAddItem, sbAllPeople, sbAssigned, sbExportToFinance, sbExported, sbFileRef,
    sbFriendInput, sbFriends, sbGetColor, sbInputMode, sbItemName, sbItemPrice, sbItems,
    sbMyTotal, sbPaidMap, sbReset, sbScanProgress, sbScanReceipt, sbScanning,
    sbSelectedFor, sbStep, sbToggleAssign, sbTotals, sbUnassigned, search, setFilterJenis,
    cashForm, handleCashMove, setCashForm,
    setFilterMonth, setForm, setInputSubTab, setSbFriendInput, setSbFriends, setSbInputMode,
    setSbItemName, setSbItemPrice, setSbItems, setSbPaidMap, setSbSelectedFor, setSbStep,
    setSearch, setShowOld, showOld
  } = props;
  return (
    <>
      <div className="hdr"><div><div className="hdr-sub">Tambah catatan</div><div className="hdr-title">Input</div></div></div>
      <div className="scroll" style={{paddingBottom:112}}>
        <div style={{display:"flex",background:"rgba(0,0,0,.35)",borderRadius:14,padding:3,border:"1px solid rgba(255,255,255,.05)",marginBottom:16}}><button onClick={()=>setInputSubTab("normal")} style={{flex:1,padding:"10px",borderRadius:11,border:"none",fontFamily:"inherit",fontSize:13,fontWeight:700,cursor:"pointer",background:inputSubTab==="normal"?"rgba(88,86,214,.18)":"none",color:inputSubTab==="normal"?"#a78bfa":"rgba(255,255,255,.3)"}}>Catat</button><button onClick={()=>setInputSubTab("cash")} style={{flex:1,padding:"10px",borderRadius:11,border:"none",fontFamily:"inherit",fontSize:13,fontWeight:700,cursor:"pointer",background:inputSubTab==="cash"?"rgba(88,86,214,.18)":"none",color:inputSubTab==="cash"?"#a78bfa":"rgba(255,255,255,.3)"}}>Atur Cash</button><button onClick={()=>setInputSubTab("split")} style={{flex:1,padding:"10px",borderRadius:11,border:"none",fontFamily:"inherit",fontSize:13,fontWeight:700,cursor:"pointer",background:inputSubTab==="split"?"rgba(88,86,214,.18)":"none",color:inputSubTab==="split"?"#a78bfa":"rgba(255,255,255,.3)"}}>Split</button></div>
        {inputSubTab==="normal" && <div className="form-card"><div className="toggle-row"><button className={"tog-btn " + (form.jenis==="Pemasukan"?"tog-in":"")} onClick={()=>setForm(f=>({...f,jenis:"Pemasukan",kategori:"Gaji",account:f.account||"QRIS"}))}>Pemasukan</button><button className={"tog-btn " + (form.jenis==="Pengeluaran"?"tog-out":"")} onClick={()=>setForm(f=>({...f,jenis:"Pengeluaran",kategori:"Makan",account:f.account||"QRIS"}))}>Pengeluaran</button></div><div className="field-label">Nominal (Rp)</div><input className="inp" inputMode="numeric" placeholder="0" value={form.nominal} onChange={e=>{ const raw=e.target.value.replace(/\D/g,""); setForm(f=>({...f,nominal:raw?parseInt(raw).toLocaleString("id-ID"):""})); }}/><div className="field-label">Tanggal</div><input className="inp" type="date" value={form.tanggal} onChange={e=>setForm(f=>({...f,tanggal:e.target.value}))}/><div className="field-label">{form.jenis==="Pemasukan"?"Masuk ke":"Bayar pakai"}</div><div className="toggle-row"><button className={"tog-btn " + ((form.account||"QRIS")==="QRIS"?"tog-in":"")} onClick={()=>setForm(f=>({...f,account:"QRIS"}))}>QRIS</button><button className={"tog-btn " + (form.account==="Cash"?"tog-in":"")} onClick={()=>setForm(f=>({...f,account:"Cash"}))}>Cash</button></div><div className="field-label">Kategori</div><div className="kat-grid">{jenisKat.map(k=><div key={k} className={"kat-item " + (form.kategori===k?"sel":"")} onClick={()=>setForm(f=>({...f,kategori:k,deskripsi:k==="Tabungan"&&!f.deskripsi.trim()?"Setor Dana Nikah":f.deskripsi}))}><div style={{fontSize:22,marginBottom:4}}>{EMOJI[k]}</div>{k}</div>)}</div><div className="field-label">Deskripsi</div><input className="inp" placeholder={form.kategori==="Tabungan"?"Setor Dana Nikah...":"Contoh: makan siang berdua..."} value={form.deskripsi} onChange={e=>setForm(f=>({...f,deskripsi:e.target.value}))}/><button className="submit-btn" onClick={handleSubmit} disabled={syncing}>{syncing?"Menyimpan...":"Simpan & Sync"}</button></div>}
        {inputSubTab==="cash" && <div className="form-card"><div className="field-label">Aksi</div><div className="toggle-row"><button className={"tog-btn " + (cashForm.mode==="withdraw"?"tog-in":"")} onClick={()=>setCashForm(f=>({...f,mode:"withdraw",deskripsi:f.deskripsi==="Setor cash ke QRIS"?"Tarik cash":f.deskripsi}))}>Tarik Cash</button><button className={"tog-btn " + (cashForm.mode==="deposit"?"tog-in":"")} onClick={()=>setCashForm(f=>({...f,mode:"deposit",deskripsi:f.deskripsi==="Tarik cash"?"Setor cash ke QRIS":f.deskripsi}))}>Setor Cash</button></div><div style={{fontSize:12,color:"rgba(255,255,255,.35)",lineHeight:1.5,margin:"-6px 0 16px"}}>{cashForm.mode==="withdraw"?"QRIS/rekening berkurang, cash bertambah. Ini bukan pengeluaran.":"Cash berkurang, QRIS/rekening bertambah. Ini bukan pemasukan."}</div><div className="field-label">Nominal (Rp)</div><input className="inp" inputMode="numeric" placeholder="0" value={cashForm.nominal} onChange={e=>{ const raw=e.target.value.replace(/\D/g,""); setCashForm(f=>({...f,nominal:raw?parseInt(raw).toLocaleString("id-ID"):""})); }}/><div className="field-label">Tanggal</div><input className="inp" type="date" value={cashForm.tanggal} onChange={e=>setCashForm(f=>({...f,tanggal:e.target.value}))}/><div className="field-label">Deskripsi</div><input className="inp" placeholder="Contoh: tarik ATM..." value={cashForm.deskripsi} onChange={e=>setCashForm(f=>({...f,deskripsi:e.target.value}))}/><button className="submit-btn" onClick={handleCashMove} disabled={syncing}>{syncing?"Menyimpan...":"Simpan Atur Cash"}</button></div>}
        {inputSubTab==="split" && <div><div style={{display:"flex",alignItems:"center",gap:6,marginBottom:20}}>{["Temen","Input","Assign","Ringkasan"].map((s,i)=><div key={s} style={{display:"flex",alignItems:"center",gap:6,flex:i<3?1:"none"}}><div style={{width:24,height:24,borderRadius:"50%",display:"flex",alignItems:"center",justifyContent:"center",fontSize:11,fontWeight:700,flexShrink:0,background:i<sbStep?"#5856d6":"rgba(255,255,255,.08)",border:i===sbStep?"1.5px solid #7c7aff":"none",color:i<sbStep?"#fff":i===sbStep?"#a78bfa":"rgba(255,255,255,.25)"}}>{i<sbStep?"ok":i+1}</div>{i<3&&<div style={{flex:1,height:2,background:i<sbStep?"#5856d6":"rgba(255,255,255,.08)",borderRadius:999}}/>}</div>)}</div>
          {sbStep===0 && <><div className="sec-title">Temen yang nitip</div><div style={{display:"flex",gap:8,marginBottom:12}}><input className="inp" style={{margin:0,flex:1}} placeholder="Nama temen..." value={sbFriendInput} onChange={e=>setSbFriendInput(e.target.value)} onKeyDown={e=>e.key==="Enter"&&sbAddFriend()}/><button onClick={sbAddFriend} style={{padding:"12px 16px",borderRadius:14,border:"none",background:"rgba(255,255,255,.8)",color:"#000",fontFamily:"inherit",fontSize:14,fontWeight:700,cursor:"pointer",flexShrink:0}}>Tambah</button></div><div style={{marginBottom:20}}>{["Gue","Pasangan",...sbFriends].map((f,i)=>{ const c=sbGetColor(f); return <span key={f} style={{display:"inline-flex",alignItems:"center",gap:6,background:c.bg,border:"1px solid " + c.color + "88",borderRadius:999,padding:"5px 12px",fontSize:12,fontWeight:700,color:c.color,marginRight:6,marginBottom:6}}>{f}{i>1&&<button onClick={()=>setSbFriends(fr=>fr.filter(x=>x!==f))} style={{background:"none",border:"none",color:"inherit",cursor:"pointer",fontSize:14,lineHeight:1,opacity:.7}}>x</button>}</span>; })}</div><button onClick={()=>setSbStep(1)} className="submit-btn">Lanjut Pilih Input</button></>}
          {sbStep===1 && !sbInputMode && <><div className="sec-title">Mau input gimana?</div><button className="submit-btn" onClick={()=>setSbInputMode("scan")}>Foto Struk</button><button className="submit-btn" onClick={()=>setSbInputMode("manual")}>Input Manual</button><button className="modal-close" onClick={()=>setSbStep(0)}>Kembali</button></>}
          {sbStep===1 && sbInputMode==="scan" && <><button className="modal-close" onClick={()=>setSbInputMode(null)}>Ganti metode</button><div className="sec-title">Foto struk belanja lo</div><input ref={sbFileRef} type="file" accept="image/*" capture="environment" style={{display:"none"}} onChange={e=>{ if(e.target.files[0]) sbScanReceipt(e.target.files[0]); e.target.value=""; }}/><div onClick={()=>!sbScanning&&sbFileRef.current.click()} style={{background:"#111",border:".5px " + (sbScanning?"solid":"dashed") + " " + (sbScanning?"#7c7aff":"rgba(255,255,255,.1)"),borderRadius:20,padding:32,marginBottom:16,textAlign:"center",cursor:sbScanning?"default":"pointer"}}>{sbScanning ? <><div style={{fontSize:14,fontWeight:700,color:"rgba(255,255,255,.4)"}}>Lagi baca struk...</div><div style={{background:"rgba(255,255,255,.08)",borderRadius:999,height:4,margin:"14px 0"}}><div style={{width:sbScanProgress + "%",height:"100%",borderRadius:999,background:"#fff",transition:"width .3s"}}/></div></> : <><div style={{fontSize:14,fontWeight:700,color:"rgba(255,255,255,.4)"}}>Tap untuk foto struk</div><div style={{fontSize:12,color:"rgba(255,255,255,.25)",marginTop:4}}>atau pilih dari galeri</div></>}</div></>}
          {sbStep===1 && sbInputMode==="manual" && <><button className="modal-close" onClick={()=>setSbInputMode(null)}>Ganti metode</button><div className="sec-title">Tambah pesanan</div><div className="form-card"><div className="field-label">Nama item</div><input className="inp" placeholder="Contoh: Kopi Susu..." value={sbItemName} onChange={e=>setSbItemName(e.target.value)}/><div className="field-label">Harga (Rp)</div><input className="inp" inputMode="numeric" placeholder="0" value={sbItemPrice} onChange={e=>{ const raw=e.target.value.replace(/\D/g,""); setSbItemPrice(raw?parseInt(raw).toLocaleString("id-ID"):""); }}/><div className="field-label">Untuk siapa?</div><div style={{display:"flex",flexWrap:"wrap",marginBottom:12}}>{sbAllPeople.map(p=>{ const c=sbGetColor(p); const sel=sbSelectedFor.includes(p); return <span key={p} onClick={()=>setSbSelectedFor(s=>s.includes(p)?s.filter(x=>x!==p):[...s,p])} style={{display:"inline-flex",alignItems:"center",background:sel?c.bg:"rgba(255,255,255,.08)",border:"1px solid " + (sel?c.color:"rgba(255,255,255,.1)"),borderRadius:999,padding:"6px 14px",fontSize:12,fontWeight:700,color:sel?c.color:"rgba(255,255,255,.3)",marginRight:6,marginBottom:6,cursor:"pointer"}}>{p}</span>; })}</div><button onClick={sbAddItem} className="submit-btn">Tambah Item</button></div>{sbItems.length>0&&<button onClick={()=>setSbStep(3)} className="submit-btn">Lanjut Ringkasan</button>}</>}
          {sbStep===2 && <><div className="sec-title">Siapa punya item ini?</div>{sbItems.map(item=><div key={item.id} className="form-card"><div style={{display:"flex",justifyContent:"space-between",marginBottom:10}}><b>{item.name}</b><b>{fmtRp(item.price)}</b></div>{sbAllPeople.map(p=>{ const c=sbGetColor(p); const sel=(sbAssigned[item.id]||[]).includes(p); return <span key={p} onClick={()=>sbToggleAssign(item.id,p)} style={{display:"inline-flex",margin:4,padding:"5px 12px",borderRadius:999,fontSize:11,fontWeight:700,cursor:"pointer",background:sel?c.bg:"rgba(255,255,255,.04)",border:"1.5px solid " + (sel?c.color:"rgba(255,255,255,.08)"),color:sel?c.color:"rgba(255,255,255,.3)"}}>{p}</span>; })}</div>)}<button onClick={()=>setSbStep(3)} disabled={sbUnassigned>0} className="submit-btn">{sbUnassigned>0?sbUnassigned + " item belum ditandai":"Lanjut Ringkasan"}</button></>}
          {sbStep===3 && <><div className="sec-title">Ringkasan tagihan</div><div className="form-card"><div className="field-label">Total struk</div><h2>{fmtRp(sbItems.reduce((s,i)=>s+i.price,0))}</h2><div className="field-label">Gue & Pasangan</div><h1>{fmtRp(Math.round(sbMyTotal))}</h1><button onClick={sbExportToFinance} disabled={sbExported} className="submit-btn">{sbExported?"Sudah dicatat":"Catat ke Finance Tracker"}</button></div>{sbFriends.filter(f=>sbTotals[f]>0).map(f=>{ const c=sbGetColor(f); const paid=sbPaidMap[f]; return <div key={f} className="form-card"><div style={{color:c.color,fontWeight:700}}>{f}</div><h2 style={{color:c.color}}>{fmtRp(Math.round(sbTotals[f]))}</h2><button onClick={()=>setSbPaidMap(m=>({...m,[f]:!m[f]}))} className="modal-close">{paid?"Tandai belum":"Tandai lunas"}</button></div>; })}<button onClick={sbReset} className="modal-close">Reset & Mulai Sesi Baru</button></>}
        </div>}
      </div>
    </>
  );
}
